### ISSUE TITLE
Update python_requires with supported Python versions

### ISSUE THREAD

**Issue by jribbens** [clokep/django-render-block#29]
You forgot to update `setup.py` to say `python_requires=">=3.6"` when you released version 0.8.

**Comment by clokep** [comment]
Ugh, so many places to update when changing these things. Sorry about that! I believe it will still run fine or Python 3.5, it just isn't supported. Thanks for pointing it out though!

**Comment by clokep** [comment]
Thanks! I've pushed a commit to fix this.
