### ISSUE TITLE
Wheel for 0.9 on PyPI empty

### ISSUE THREAD

**Issue by Natureshadow** [clokep/django-render-block#34]
The wheel released to PyPI a few hours ago does not contain any code, breaking downstreams that use semantic versioning or unlocked dependencies.

Please also consider moving to something >=1.0 so semver works.

**Comment by clokep** [comment]
FYI I've yanked 0.9, I'll release a 0.9.1 with the fixed wheel. (The source dist should worked, but there was nothing dramatic in it, anyway I'll do another release later.)

**Comment by clokep** [comment]
I've just pushed 0.9.1 which should work. Thanks for letting me know about this issue and my apologies for causing it! Please shout if you see any problems.

**Comment by Natureshadow** [comment]
Thank you for fixing this quickly! Accidents can happen; what counts is the way they are handled.

**Comment by clokep** [comment]
You're welcome! Thank you for reporting and the fix (and understanding)! 🙇
