### ISSUE TITLE
Template inheritance problem

### ISSUE THREAD

**Issue by aericson** [clokep/django-render-block#7]
Hey,

can you please take a look at https://github.com/aericson/django-render-block/commit/40e5a4d8d7e78675a819fc66d9227693d5e3dd3f
This test fails.

Shouldn't this be supported?

Thanks!

**Comment by clokep** [comment]
At first glance it looks like it should be, yes.

**Comment by dkopitsa** [comment]
I have same problem. 

I have two templates.
'base.email' :
```django
{% block subject %}Email subject{% endblock %}
{% block html %}
    <html>
     ..skip..  
    {% block html_content %}{%endblock %}
   ..skip..
    </html>
{% endblock %}
```

and 'test.email':
```django
{% extends "base.email" %}
{% block html_content %}
<h1>Hello world</h1>
{% endblock %}
```
I expect that render_block_to_string('test.email', 'html') returns full html code with text 'hello world', 
but I only get html without block html_content

**Comment by clokep** [comment]
I think what's happening is that we:
* Check the sub-template for the black.
* The black isn't found so we check the base template.
* We find the block and render it using only data from the base template.

Clearly the last step here is wrong and that we need to be using the block from the sub-template here.

**Comment by clokep** [comment]
Thanks for the bug report, by the way! I was sure I had missed some cases in my test-cases. Clearly you found one!

**Comment by clokep** [comment]
I have this mostly fixed.

**Comment by clokep** [comment]
@aericson @dkopitsa Thanks for the reports! I just merged a PR (#8) which fixes this. There's a couple of minor clean-ups I want to do, but I should be able to do a release in the next few days. (Feel free to poke me if I don't!)

**Comment by dkopitsa** [comment]
It works for me. Thank you very much!

**Comment by aericson** [comment]
:clap:

**Comment by clokep** [comment]
Just pushed version 0.5 with these changes. Thanks for confirming it works!
